backend:
  name: git-gateway
  branch: master

media_folder: _data/media

collections:
  - name: "verfrus"
    label: "Frutas y Verduras"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - name: "verfrucontent"
        label: "Frutas y Verduras Content"
        file: "public/_data/verfru.json"
        fields:
          - label: "Fruta/Verdura"
            name: verfru
            widget: list
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - label: "Type"
                name: "type"
                widget: "select"
                options: ["Fruta", "Verdura", "Legumbre", "Raíz", "Hierba Aromática", "Cereal"]
              - { label: "Content", name: "content", widget: "markdown", required: false }
              - { label: "Recipes Link", name: "link", widget: "string", required: false }
              - { label: "Image", name: "image", widget: "image", required: false }
              - label: "Seasons"
                name: "seasons"
                widget: "list"
                fields:
                  - label: "Season"
                    name: "season"
                    widget: "select"
                    options:
                      - { label: "Verano", value: "0" }
                      - { label: "Otoño", value: "1" }
                      - { label: "Invierno", value: "2" }
                      - { label: "Primavera", value: "3" }
                  - label: "When"
                    name: "when"
                    widget: "select"
                    options:
                      - { label: "All season", value: "0" }
                      - { label: "First part", value: "1" }
                      - { label: "Last part", value: "2" }
                    default: ["All season"]
              - { label: "First month", name: "fdate", widget: "date", default: "", format: "M", required: false }
              - { label: "Last month", name: "ldate", widget: "date", default: "", format: "M", required: false }
